### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user01",
  "userName": "윤수빈",
  "userPass": "pass01",
  "userRole": "USER"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "user01",
  "userPass": "pass01"
}

### GET 요청
GET http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE2Nzg5MjgzNjk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJvaGdpcmFmZmVycyB0b2tlbiA6IDciLCJ1c2VyTmFtZSI6IuycpOyImOu5iCIsInVzZXJSb2xlIjoiVVNFUiIsImV4cCI6MTcxNjg3NTY4MywidXNlcklkIjoidXNlcjAxIn0.YDNbxnLgl3QMIwuPNssigautvgUgHOc5iEBlY5xqwVU

### POST 요청
POST http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE2Nzg5MjgzNjk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJvaGdpcmFmZmVycyB0b2tlbiA6IDciLCJ1c2VyTmFtZSI6IuycpOyImOu5iCIsInVzZXJSb2xlIjoiVVNFUiIsImV4cCI6MTcxNjg3NTY4MywidXNlcklkIjoidXNlcjAxIn0.YDNbxnLgl3QMIwuPNssigautvgUgHOc5iEBlY5xqwVU